In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import uproot
import awkward as ak
import os
from utils import *

In [2]:
path  = "/Users/cpare/Downloads/val_5M/HToBB_120.root"
HtoBB = uproot.open(path)
HtoCC = uproot.open("/Users/cpare/Downloads/val_5M/HToCC_122.root")
# ZJets = uproot.open("/Users/cpare/Downloads/val_5M/ZJetsToNuNu_120.root")

In [3]:
# HtoBB.keys()
BB_branch = HtoBB['tree']
BB_branch.keys()

['part_px',
 'part_py',
 'part_pz',
 'part_energy',
 'part_deta',
 'part_dphi',
 'part_d0val',
 'part_d0err',
 'part_dzval',
 'part_dzerr',
 'part_charge',
 'part_isChargedHadron',
 'part_isNeutralHadron',
 'part_isPhoton',
 'part_isElectron',
 'part_isMuon',
 'label_QCD',
 'label_Hbb',
 'label_Hcc',
 'label_Hgg',
 'label_H4q',
 'label_Hqql',
 'label_Zqq',
 'label_Wqq',
 'label_Tbqq',
 'label_Tbl',
 'jet_pt',
 'jet_eta',
 'jet_phi',
 'jet_energy',
 'jet_nparticles',
 'jet_sdmass',
 'jet_tau1',
 'jet_tau2',
 'jet_tau3',
 'jet_tau4',
 'aux_genpart_eta',
 'aux_genpart_phi',
 'aux_genpart_pid',
 'aux_genpart_pt',
 'aux_truth_match']

In [4]:
CC_branch = HtoCC['tree']
CC_branch.keys()
arr = CC_branch['part_px'].array()
arr = np.array(arr)
type(arr)

ValueError: in ListOffsetArray64, cannot convert to RegularArray because subarray lengths are not regular

(https://github.com/scikit-hep/awkward-1.0/blob/1.8.0/src/cpu-kernels/awkward_ListOffsetArray_toRegularArray.cpp#L22)

## Zero-pad the PARTICLES

In [5]:

CC_branch = HtoCC['tree']

for i in CC_branch.keys():
    if "jet" in i:
        arr = CC_branch[i].array()
        arr = ak.to_numpy(arr)
        print(arr)
        print("This the type of the array: ", type(arr))
        print("This is the length of the array: ",len(arr))
# arr2 = pd.DataFrame(CC['jet_eta'].array())
# arr2 = np.array(arr2)
# arr2

# new = list(arr2)
# new = np.array(new)
# new

[712.62054 523.09674 587.05774 ... 629.4652  663.3251  660.9326 ]
This the type of the array:  <class 'numpy.ndarray'>
This is the length of the array:  100000
[ 0.66018033 -0.11323062 -0.02584227 ... -0.5359105  -1.0891047
  0.80419046]
This the type of the array:  <class 'numpy.ndarray'>
This is the length of the array:  100000
[ 1.0990121   0.06909209 -1.6507215  ... -0.92439324  0.36931244
 -0.59055436]
This the type of the array:  <class 'numpy.ndarray'>
This is the length of the array:  100000
[ 878.40295  544.3763   593.29297 ...  731.1771  1104.1888   895.9539 ]
This the type of the array:  <class 'numpy.ndarray'>
This is the length of the array:  100000
[47. 27. 24. ... 38. 42. 79.]
This the type of the array:  <class 'numpy.ndarray'>
This is the length of the array:  100000
[ 91.37938  137.73257    9.488261 ...  61.380795 124.18896   75.9391  ]
This the type of the array:  <class 'numpy.ndarray'>
This is the length of the array:  100000
[0.13239832 0.20080546 0.06185093 ... 0

In [6]:
arr_jet = BB_branch['jet_energy'].array()
arr_jet = np.array(arr_jet)
print(arr_jet)
print(len(arr_jet))
print(arr_jet[0])
print(arr_jet[1])

[637.4366  793.0102  744.49725 ... 600.47424 995.3459  819.13745]
100000
637.4366
793.0102


In [7]:
#BB.keys()
arr_awk = BB_branch['part_deta'].array()
arr = list(arr_awk)
# type(arr)
# # arr1 = ak.to_numpy(arr)
# len(arr)
# arr2 = Z['part_isElectron'].array()
# arr3 = Z['part_isPhoton'].array()

# type(arr2)


# arr = np.array([arr2,arr3])
print(arr[0])
print(len(arr[0]))
print(arr[1])
print(len(arr[1]))
print(len(arr))

[-0.333, 0.139, 0.167, -0.346, 0.338, ... -0.186, 0.0767, -0.0485, -0.158, -0.282]
53
[-0.195, 0.242, -0.182, -0.025, -0.149, ... 0.0238, 0.00561, -0.179, -0.173, -0.209]
68
100000


In [8]:
new_list = []
for i in arr:
    i = list(i)
    new_list.append(i)

KeyboardInterrupt: 

In [12]:
print(type(new_list[1]))
print(new_list[1])

<class 'list'>
[-0.19503355026245117, 0.24239569902420044, -0.18173280358314514, -0.025000810623168945, -0.1493472456932068, 0.06976354122161865, -0.023978829383850098, -0.05407005548477173, 0.006401956081390381, -0.15784010291099548, -0.17233574390411377, -0.1615133285522461, -0.009202897548675537, -0.014401674270629883, 0.039802491664886475, -0.18775337934494019, -0.1136854887008667, 0.03374183177947998, 0.06384932994842529, -0.01844853162765503, -0.06585395336151123, -0.12259882688522339, 0.01043635606765747, 0.09242218732833862, -0.025417864322662354, -0.19619610905647278, 0.027174830436706543, 0.41238194704055786, 0.2415088415145874, 0.187991201877594, -0.1906132698059082, 0.030604422092437744, 0.013736307621002197, -0.21283027529716492, -0.05641740560531616, 0.07764416933059692, 0.043418824672698975, 0.3652522563934326, 0.2301589846611023, -0.16478115320205688, 0.35856419801712036, 0.08965730667114258, 0.1163296103477478, -0.22454127669334412, 0.08775657415390015, 0.1311815977096

In [9]:
def findMaxLengthList(lst):
    maxLength = max(len(x) for x in lst)

    return maxLength





In [10]:
list4 = [[12,45,54], [12,1]]
max_1 = findMaxLengthList(list4)
max_1

3

In [11]:
def pad_val(
    arr: ak.Array,
    target: int,
    value: float,
    axis: int = 0,
    to_numpy: bool = True,
    clip: bool = True,
):
    """
    pads awkward array up to ``target`` index along axis ``axis`` with value ``value``,
    optionally converts to numpy array
    """
    ret = ak.fill_none(ak.pad_none(arr, target, axis=axis, clip=clip), value, axis=axis)
    return ret.to_numpy() if to_numpy else ret

In [12]:
list_ex = [1,2,3,4,5]

pad_list = np.pad(new_list[0], (136 - len(new_list[0]),0), 'constant', constant_values = 0)

print(pad_list)
print(len(pad_list))
pad_list_arr = np.array(pad_list)
print(type(pad_list_arr))
print("This is the shape: ", pad_list_arr.shape)

[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.         -0.33261487
  0.13884914  0.16689381 -0.34617624  0.33798349  0.34917706 -0.36195976
 -0.36011

In [13]:
type(new_list[0])

list

In [14]:
arr_awk = BB_branch['part_deta'].array()
arr = list(arr_awk)

## Brute Force Method
def zero_padding(lst):
    returned_list = []
    for sub_list in lst:
        sub_list = list(sub_list)
        returned_list.append(sub_list);
    
    padded_list = []
    max_value = findMaxLengthList(returned_list)
    for i in returned_list:
        #print(type(i))
        pad_list = np.pad(i, (0,max_value - len(i)), 'constant', constant_values = 0)
        padded_list.append(pad_list)
    
    zero_padded_arr = np.array(padded_list)
    
    return zero_padded_arr


    
zero_pad_arr = zero_padding(arr)

# pad_list = np.pad(new_list[0], (136 - len(new_list[0]),0), 'constant', constant_values = 0)

In [22]:
len(zero_pad_arr[55])
zero_pad_arr[0]


array([-0.33261487,  0.13884914,  0.16689381, -0.34617624,  0.33798349,
        0.34917706, -0.36195976, -0.36011371,  0.14561334,  0.10209948,
        0.12327558, -0.32392117,  0.06296283,  0.32214826, -0.34294909,
       -0.33581877,  0.10832328,  0.29073238,  0.1595732 ,  0.18522918,
        0.13907623, -0.28958672,  0.05045712,  0.34282684, -0.29096931,
       -0.37713552,  0.12561399,  0.06387076,  0.19321933,  0.13469011,
        0.27635479,  0.12613833, -0.14884725, -0.24919088,  0.31138563,
        0.32054645,  0.16568625, -0.31374669,  0.25473982, -0.672616  ,
        0.11304051,  0.05192709,  0.27473116,  0.51374203, -0.29222512,
        0.11761698,  0.08965781,  0.15728977, -0.18610013,  0.07667631,
       -0.04854403, -0.15753093, -0.28155357,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [16]:
def pad_val(
    arr: ak.Array,
    target: int,
    value: float,
    axis: int = 0,
    to_numpy: bool = True,
    clip: bool = True,
):
    """
    pads awkward array up to ``target`` index along axis ``axis`` with value ``value``,
    optionally converts to numpy array
    """
    ret = ak.fill_none(ak.pad_none(arr, target, axis=axis, clip=clip), value, axis=axis)
    return ret.to_numpy() if to_numpy else ret

a = pad_val(arr[55], 136, 0.0)
len(a)

136

In [18]:
def zero_padding_raghav(lst):
    returned_list = []
    for sub_list in lst:
        sub_list = list(sub_list)
        returned_list.append(sub_list);
    
    #padded_list = []
    final_padd_arr = np.array([])
    max_value = findMaxLengthList(returned_list)
    for arr_awk in lst:
        padded = pad_val(arr_awk, max_value, 0.0)
        final_padd_arr = np.append(final_padd_arr,padded)

    return final_padd_arr
    

In [83]:
emp = np.array([])
h = np.array([12,23])
emp = np.append(emp,h)
emp

array([12., 23.])

In [19]:
x = zero_padding_raghav(arr)

KeyboardInterrupt: 

In [9]:
arr2 = BB_branch['part_deta'].array()
arr2 = list(arr2)
arr2_new = np.array(arr2, dtype=object)
print(type(arr2_new))

<class 'numpy.ndarray'>


In [35]:
print(arr2_new)

[<Array [-0.333, 0.139, ... -0.158, -0.282] type='53 * float32'>
 <Array [-0.195, 0.242, ... -0.173, -0.209] type='68 * float32'>
 <Array [-0.0862, 0.0528, ... 0.189, 0.196] type='26 * float32'> ...
 <Array [0.189, -0.162, ... -0.147, 0.0777] type='24 * float32'>
 <Array [-0.0651, -0.0302, ... 0.0745, 0.00678] type='45 * float32'>
 <Array [-0.0765, -0.0801, ... -0.0563, -0.0098] type='21 * float32'>]


In [ ]:


directory = "/Users/cpare/Downloads/val_5M"
answer = input('For jet feautures enter "jet" and for particle features enter "part"')
for filename in os.listdir(directory):
    f = os.path.join(directory,filename)
    file = uproot.open(f)
    x = file['tree']
    for i in x.keys():
        if answer == "part":
            if "part" in i:
                print(i)
        if answer == "jet":
            if "jet" in i:
                print(i)

jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_np

In [ ]:
file = "JetClass_Pythia_val_5M.tar"
record_id = 6619768
file_url = getZenodoFileURL(record_id, file)
file_url

'https://zenodo.org/api/files/e74892f2-1542-492b-b753-1e8f86c1d2ea/JetClass_Pythia_val_5M.tar'

In [ ]:
data_dir = "/Users/cpare/Downloads"
dataset_name  = "JetClass"
real_file_name = "val_5M"
filePath = checkDownloadZenodoDataset(data_dir, dataset_name, record_id, real_file_name)
filePath

'/Users/cpare/Downloads/val_5M'

In [ ]:

def getData(split, jet_type, jet_features, particle_features, data_dir):
    valid_matrix_features = np.zeros((1,100000))
    record_id = 6619768
    if (split == "valid"):
        dataset_name = "JetClass validation"
        file_name = "val_5M"
        filePath = checkDownloadZenodoDataset(data_dir, dataset_name, record_id = record_id, key = file_name)
        print(filePath)
        for filename in os.listdir(filePath):
            f  = os.path.join(filePath, filename)
            if "b" in jet_type:
                if ("BB") in f:
                    open_file = uproot.open(f)
                    branch = open_file['tree']
                    for i in branch.keys():
                        for feature in jet_features:
                            if feature in i:
                                arr = branch[i].array()
                                arr = ak.to_numpy(arr)
                                valid_matrix_features = np.vstack([valid_matrix_features, arr])
    elif(split == "train"):
        part = input("Enter the subset value of the training data (0-9):")
        dataset_name = f" JetClass training_part{part}"
        file_name = "val_10M"
        filePath = checkDownloadZenodoDataset(data_dir=data_dir,dataset_name=dataset_name, record_id = record_id, key = file_name)
        for file in os.listdir(filePath):
            f = os.path.join(filePath, file)
            if 

    elif(split == "test"):
        pass
    else:
        split = "all"
    
    valid_matrix_features = valid_matrix_features.T
    valid_matrix_features_new = np.delete(valid_matrix_features,0, axis = 1)
    return valid_matrix_features_new




            




        
        
        
        



In [ ]:
split = "valid"
# jet_type = ["b","c", "g","w"]
jet_type = ["b", "c"]
jet_features = ["jet_pt","jet_energy", "jet_eta"]
particle_features = ["px","py","pz"]
data_dir = "/Users/cpare/Downloads"


testing  = getData(split,jet_features, particle_features, data_dir)
print(testing)
testing.shape
# df = pd.DataFrame(testing)
# df.head()
# #df.shape

/Users/cpare/Downloads/val_5M
[[ 0.00000000e+00  5.69305908e+02  2.80798256e-01 ...  5.07731934e+02
  -1.33122468e+00  1.03149036e+03]
 [ 0.00000000e+00  6.25874695e+02 -6.30695403e-01 ...  5.22395752e+02
  -6.41480625e-01  6.46075562e+02]
 [ 0.00000000e+00  7.17363464e+02  2.26348951e-01 ...  5.13242004e+02
  -1.08207035e+00  8.53897583e+02]
 ...
 [ 0.00000000e+00  5.46770325e+02 -3.82432193e-01 ...  6.27279358e+02
  -5.49419224e-01  7.37603027e+02]
 [ 0.00000000e+00  7.35002930e+02 -8.13788354e-01 ...  6.15022766e+02
   1.88130125e-01  6.39374023e+02]
 [ 0.00000000e+00  5.82261047e+02 -8.54874492e-01 ...  8.90147583e+02
   1.31683871e-01  9.06058777e+02]]


(100000, 16)

In [ ]:
testing_new = np.delete(testing, 0, axis=1)
testing_new.shape
df = pd.DataFrame(testing_new)
df.head()

0         1            2           3         4            5   \
0  569.305908  0.280798   637.436584  594.538940 -1.896163  2026.914429   
1  625.874695 -0.630695   793.010193  538.692993 -0.581693   643.553772   
2  717.363464  0.226349   744.497253  654.018799  1.908742  2261.170166   
3  623.471069  0.731986   810.579895  509.543762 -1.047998   823.590088   
4  583.732361  1.399453  1260.712891  571.258606 -1.242284  1078.042358   

           6         7            8           9         10           11  \
0  605.414062 -1.827487  1935.098999  501.743073  0.833796   697.273254   
1  633.106812 -1.166031  1136.068726  683.190796 -1.524658  1646.926758   
2  500.897552  0.289145   529.736572  500.141663  0.623858   610.014404   
3  553.593201 -0.062218   566.985413  842.556580  1.341919  1725.054688   
4  660.869812  0.000299   702.465515  549.738525  0.601622   663.438049   

           12        13           14  
0  507.731934 -1.331225  1031.490356  
1  522.395752 -0.641481   646.075562  
2  513.242004 -1.082070   853.897583  
3  732.821228 -0.105728   749.381836  
4  550.275146 -0.469934   617.656250

In [ ]:

a = np.zeros((1,3))
new = [34,5,1]
a = np.vstack([a,new])
a


NameError: name 'np' is not defined

In [ ]:
split = "valid"
# jet_type = ["b","c", "g","w"]
jet_type = ["b", "c"]
jet_features = ["jet_pt","jet_energy", "jet_eta"]
particle_features = ["px","py","pz"]
data_dir = "/Users/cpare/Downloads"



def getData(split, jet_type, jet_features, particle_features, data_dir):
    valid_matrix_features = np.zeros((1,100000))
    record_id = 6619768
    if (split == "valid"):
        dataset_name = "JetClass validation"
        file_name = "val_5M"
        filePath = checkDownloadZenodoDataset(data_dir, dataset_name, record_id = record_id, key = file_name)
        print(filePath)
        for filename in os.listdir(filePath):
            f  = os.path.join(filePath, filename)
            if "b" in jet_type:
                if ("BB") in f:
                    open_file = uproot.open(f)
                    branch = open_file['tree']
                    for i in branch.keys():
                        for feature in jet_features:
                            if feature in i:
                                arr = branch[i].array()
                                arr = ak.to_numpy(arr)
                                valid_matrix_features = np.vstack([valid_matrix_features, arr])
    elif(split == "train"):
        part = input("Enter the subset value of the training data (0-9):")
        dataset_name = f" JetClass training_part{part}"
        file_name = "val_10M"
        filePath = checkDownloadZenodoDataset(data_dir=data_dir,dataset_name=dataset_name, record_id = record_id, key = file_name)
        for file in os.listdir(filePath):
            f = os.path.join(filePath, file)
            if 

    elif(split == "test"):
        pass
    else:
        split = "all"
    
    valid_matrix_features = valid_matrix_features.T
    valid_matrix_features_new = np.delete(valid_matrix_features,0, axis = 1)
    return valid_matrix_features_new


## Testing Functions

In [ ]:
jet_type = "b", "c"
a = checkStrToList(jet_type)
print(type(a))
print(a)
# print(type(jet_type))

<class 'tuple'>
('b', 'c')


In [ ]:
jet_types = ["g","q","t","w","z"]

jet_type = ["q"]
b = checkConvertElements(jet_type, valid_types=jet_types, ntype="jet type")
b


particle_features, jet_features = checkStrToList(particle_features, jet_features)
print(particle_features)
print(jet_features)

use_particle_features, use_jet_features = checkListNotEmpty(particle_features, jet_features)

print(use_jet_features)
print(use_particle_features)

['px', 'py', 'pz']
['jet_pt', 'jet_energy', 'jet_eta']
3
3


a = 