In [39]:
import numpy as np
import pandas as pd
import matplotlib as plt
import uproot
import awkward as ak

In [40]:
path  = "/Users/cpare/Downloads/val_5M/HToBB_120.root"
HtoBB = uproot.open(path)
HtoCC = uproot.open("/Users/cpare/Downloads/val_5M/HToCC_122.root")
# ZJets = uproot.open("/Users/cpare/Downloads/val_5M/ZJetsToNuNu_120.root")

In [41]:
# HtoBB.keys()
BB = HtoBB['tree']
BB.keys()

['part_px',
 'part_py',
 'part_pz',
 'part_energy',
 'part_deta',
 'part_dphi',
 'part_d0val',
 'part_d0err',
 'part_dzval',
 'part_dzerr',
 'part_charge',
 'part_isChargedHadron',
 'part_isNeutralHadron',
 'part_isPhoton',
 'part_isElectron',
 'part_isMuon',
 'label_QCD',
 'label_Hbb',
 'label_Hcc',
 'label_Hgg',
 'label_H4q',
 'label_Hqql',
 'label_Zqq',
 'label_Wqq',
 'label_Tbqq',
 'label_Tbl',
 'jet_pt',
 'jet_eta',
 'jet_phi',
 'jet_energy',
 'jet_nparticles',
 'jet_sdmass',
 'jet_tau1',
 'jet_tau2',
 'jet_tau3',
 'jet_tau4',
 'aux_genpart_eta',
 'aux_genpart_phi',
 'aux_genpart_pid',
 'aux_genpart_pt',
 'aux_truth_match']

In [164]:
CC = HtoCC['tree']
CC.keys()
arr = CC['part_px'].array()
arr = ak.to_numpy(arr)
arr

ValueError: in ListOffsetArray64, cannot convert to RegularArray because subarray lengths are not regular

(https://github.com/scikit-hep/awkward-1.0/blob/1.8.0/src/cpu-kernels/awkward_ListOffsetArray_toRegularArray.cpp#L22)

In [152]:
HtoCC.keys()
CC = HtoCC['tree']

for i in CC.keys():
    if "jet" in i:
        arr = CC[i].array()
        arr = ak.to_numpy(arr)
        print(arr)
# arr2 = pd.DataFrame(CC['jet_eta'].array())
# arr2 = np.array(arr2)
# arr2

# new = list(arr2)
# new = np.array(new)
# new

[712.62054 523.09674 587.05774 ... 629.4652  663.3251  660.9326 ]
[ 0.66018033 -0.11323062 -0.02584227 ... -0.5359105  -1.0891047
  0.80419046]
[ 1.0990121   0.06909209 -1.6507215  ... -0.92439324  0.36931244
 -0.59055436]
[ 878.40295  544.3763   593.29297 ...  731.1771  1104.1888   895.9539 ]
[47. 27. 24. ... 38. 42. 79.]
[ 91.37938  137.73257    9.488261 ...  61.380795 124.18896   75.9391  ]
[0.13239832 0.20080546 0.06185093 ... 0.10510892 0.14286892 0.18611443]
[0.03577862 0.01662678 0.02938212 ... 0.05823926 0.06459513 0.12152812]
[0.02623351 0.01551823 0.02206516 ... 0.03502854 0.049146   0.09883508]
[0.02162579 0.01414961 0.02008151 ... 0.03000532 0.03791072 0.08564419]


In [120]:
new

array([<Array [234, 72.2, 53.9, ... 1.21, 1.24, 1.13] type='47 * float32'>,
       <Array [97.8, 77, 60.7, ... 1.36, 1.22, 0.914] type='27 * float32'>,
       <Array [122, 90, 70.7, ... 1.52, 1.33, 1.02] type='24 * float32'>,
       ...,
       <Array [184, 135, 82.4, ... 2, 1.63, 1.39] type='38 * float32'>,
       <Array [166, 75.5, 68.1, ... 2.57, 3.66, 1.82] type='42 * float32'>,
       <Array [128, 52.5, 49.8, ... 1.67, 1.38, 1.13] type='79 * float32'>],
      dtype=object)

In [44]:
ZJets.keys()
Z = ZJets['tree']
Z.keys()

NameError: name 'ZJets' is not defined

In [46]:
#BB.keys()
arr = BB['part_deta'].array()
# arr = np.array(arr)
# type(arr)
# arr1 = ak.to_numpy(arr)
len(arr)
# arr2 = Z['part_isElectron'].array()
# arr3 = Z['part_isPhoton'].array()

# type(arr2)


# arr = np.array([arr2,arr3])
# print(arr)

100000

In [ ]:
import numpy as np
X = np.array([0,2,5,1,5,7,8])
data = np.array([])
Y = np.array([])
Z = np.array([])

def filter1(X,Y):
    for i in X:
        if(i== 0 or i==5):
            Y = np.append(Y,i)
    return Y


def filter2(Y, Z):
    for i in Y:
        if(i==5):
            i = 1
            Z = np.append(Z,i)
        if(i==0):
            Z = np.append(Z,i)
    return Z


arr = filter1(X,Y)
print(arr)

arr2 = filter2(arr,Z)
print(arr2)


[0. 5. 5.]
[0. 1. 1.]


In [ ]:
def getData():
    pass
    

In [ ]:
import numpy as np
import uproot
import os
import pandas as pd
import matplotlib as plt


directory = "/Users/cpare/Downloads/val_5M"
answer = input('For jet feautures enter "jet" and for particle features enter "part"')
for filename in os.listdir(directory):
    f = os.path.join(directory,filename)
    file = uproot.open(f)
    x = file['tree']
    for i in x.keys():
        if answer == "part":
            if "part" in i:
                print(i)
        if answer == "jet":
            if "jet" in i:
                print(i)

jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_nparticles
jet_sdmass
jet_tau1
jet_tau2
jet_tau3
jet_tau4
jet_pt
jet_eta
jet_phi
jet_energy
jet_np

In [ ]:
directory = "/Users/cpare/Downloads/val_5M"
len(directory)

29

In [ ]:
d = getData(directory)
d

'jet_pt'

In [ ]:
list1 = [1,2,3,4]
list2 = [5,5,7,8]

arr = np.array([list1,list2])
print(arr)

[[1 2 3 4]
 [5 5 7 8]]


In [ ]:
def sum(a, b):
    return a + b

In [ ]:
values = { 'a': 1, 'b': 2 }
s = sum(**values)
s

3

In [ ]:
from utils import *

In [102]:
file = "JetClass_Pythia_val_5M.tar"
record_id = 6619768
file_url = getZenodoFileURL(record_id, file)
file_url

'https://zenodo.org/api/files/e74892f2-1542-492b-b753-1e8f86c1d2ea/JetClass_Pythia_val_5M.tar'

In [103]:
data_dir = "/Users/cpare/Downloads"
dataset_name  = "JetClass"
real_file_name = "val_5M"
filePath = checkDownloadZenodoDataset(data_dir, dataset_name, record_id, real_file_name)
filePath

'/Users/cpare/Downloads/val_5M'

In [ ]:
import os
import uproot

In [158]:
split = "valid"
# jet_type = ["b","c", "g","w"]
jet_type = ["b", "c"]
jet_features = ["jet_pt","jet_energy", "jet_eta"]
particle_features = ["px","py","pz"]
real_file_name = "val_5M"


data_dir = "/Users/cpare/Downloads"
def getData(split, jet_features, particle_features, data_dir):
    train_matrix = np.array([[]])
    valid_matrix_features = np.zeros((1,100000))
    valid_matrix_particle = np.array([[]])
    test_matrix = np.array([[]])
    record_id = 6619768
    if (split == "valid"):
        dataset_name = "JetClass validation"
        file = "JetClass_Pythia_val_5M.tar"
        filePath = checkDownloadZenodoDataset(data_dir, dataset_name, record_id, real_file_name)
        print(filePath)
        for filename in os.listdir(filePath):
            f  = os.path.join(filePath, filename)
            if "b" in jet_type:
                if ("BB") in f:
                    open_file = uproot.open(f)
                    branch = open_file['tree']
                    for i in branch.keys():
                        for feature in jet_features:
                            if feature in i:
                                arr = branch[i].array()
                                arr = ak.to_numpy(arr)
                                valid_matrix_features = np.vstack([valid_matrix_features, arr])
    
    valid_matrix_features = valid_matrix_features.T
    return valid_matrix_features




            




        
        
        
        



In [169]:
testing  = getData(split, jet_features, particle_features, data_dir)
print(testing)
# df = pd.DataFrame(testing)
# df.head()
#df.shape

/Users/cpare/Downloads/val_5M
[[ 0.00000000e+00  5.69305908e+02  2.80798256e-01 ...  5.07731934e+02
  -1.33122468e+00  1.03149036e+03]
 [ 0.00000000e+00  6.25874695e+02 -6.30695403e-01 ...  5.22395752e+02
  -6.41480625e-01  6.46075562e+02]
 [ 0.00000000e+00  7.17363464e+02  2.26348951e-01 ...  5.13242004e+02
  -1.08207035e+00  8.53897583e+02]
 ...
 [ 0.00000000e+00  5.46770325e+02 -3.82432193e-01 ...  6.27279358e+02
  -5.49419224e-01  7.37603027e+02]
 [ 0.00000000e+00  7.35002930e+02 -8.13788354e-01 ...  6.15022766e+02
   1.88130125e-01  6.39374023e+02]
 [ 0.00000000e+00  5.82261047e+02 -8.54874492e-01 ...  8.90147583e+02
   1.31683871e-01  9.06058777e+02]]


In [74]:
split = "valid"
# jet_type = ["b","c", "g","w"]
jet_type = ["b", "c"]
jet_features = ["jet_pt","jet_energy", "jet_eta"]
particle_features = ["px","py","pz"]
real_file_name = "val_5M"


data_dir = "/Users/cpare/Downloads"
def getData2(split, jet_features, particle_features, data_dir):
    train_matrix = np.array([[]])
    valid_matrix_features = np.zeros((1,100000))
    valid_matrix_particle = np.array([[]])
    test_matrix = np.array([[]])
    record_id = 6619768
    if (split == "valid"):
        dataset_name = "JetClass validation"
        file = "JetClass_Pythia_val_5M.tar"
        filePath = checkDownloadZenodoDataset(data_dir, dataset_name, record_id, real_file_name)
        print(filePath)
        for filename in os.listdir(filePath):
            f  = os.path.join(filePath, filename)
            if "b" in jet_type:
                if ("BB") in f:
                    open_file = uproot.open(f)
                    branch = open_file['tree']
                    for i in branch.keys():
                        for feature in jet_features:
                            if feature in i:
                                arr = branch[i].array()
                                arr = ak.to_numpy(arr)
                                valid_matrix_features = np.vstack([valid_matrix_features, arr])
    
    valid_matrix_features = valid_matrix_features.T
    return valid_matrix_features

array([[1, 1],
       [2, 2],
       [3, 9]])

In [87]:
a = np.zeros((1,3))
new = [34,5,1]
a = np.vstack([a,new])
a


array([[ 0.,  0.,  0.],
       [34.,  5.,  1.]])

In [57]:
jet_features = ["pta","energy", "eta"]
len(jet_features)


np.array([12,1])
jet_matrix = np.zeros((2,len(jet_features)))
jet_matrix.shape

(2, 3)