In [ ]:
import h5py
import hdf5plugin
import numpy as np

f = h5py.File("/Users/cpare/Downloads/val.h5", "r")

f.keys()
f.shape

# f["table"].keys()

# f["table"]["_i_table"].keys()
# f["table"]["_i_table"]["index"].keys()

# table = np.array(f["table"]["table"])

# table

# table[0][0]
# table[0][1]
# table[0][2]

# # Pandas

# import pandas as pd

# pdtable = pd.read_hdf("/Users/raghav/Downloads/val.h5", key="table")
# pdtable

# values = pdtable.values
# values.shape

# particle_feats = values[:, :800].reshape(-1, 200, 4)
# jet_feats = values[:, 800:804]
# isTop = values[:, -1]

: 

In [ ]:
f.keys()

<KeysViewHDF5 ['table']>

: 

In [ ]:
f['table'].keys()

<KeysViewHDF5 ['_i_table', 'table']>

: 

In [ ]:
f['table']['_i_table'].keys()

<KeysViewHDF5 ['index']>

: 

In [ ]:
f["table"]["_i_table"]["index"].keys()

<KeysViewHDF5 ['abounds', 'bounds', 'indices', 'indicesLR', 'mbounds', 'mranges', 'ranges', 'sorted', 'sortedLR', 'zbounds']>

: 

In [ ]:
table = np.array(f["table"]["table"])
table

NameError: name 'np' is not defined

: 

In [ ]:
print(table[0][0])
print(table[0][1])

436
[ 2.18364243e+02 -1.72341858e+02  1.10129105e+02 -7.65036240e+01
  1.53661118e+02 -1.11320465e+02  9.31679688e+01 -5.03907127e+01
  7.67080536e+01 -5.65237007e+01  4.61272926e+01 -2.36953487e+01
  6.41816711e+01 -4.74191170e+01  3.87683411e+01 -1.91762753e+01
  5.79732666e+01 -4.18407707e+01  3.50211868e+01 -1.95899448e+01
  3.62938805e+01 -2.65304146e+01  2.19224472e+01 -1.15234156e+01
  1.09965315e+01 -2.71315145e+00  1.05449896e+01 -1.53808486e+00
  5.20679903e+00 -3.69272614e+00  3.01316810e+00 -2.09650874e+00
  4.95381403e+00 -3.36913300e+00  2.98500180e+00 -2.06856966e+00
  4.29062700e+00 -3.30971217e+00  2.35012317e+00 -1.39003766e+00
  3.79965448e+00 -2.70908237e+00  2.51254916e+00 -8.86196434e-01
  1.99092388e+00 -1.20586193e+00  1.21221972e+00 -1.01990104e+00
  1.70320201e+00 -1.24518943e+00  1.04613280e+00 -5.05970955e-01
  1.87011206e+00 -5.49257398e-01  1.39683723e+00 -1.11556327e+00
  1.32365847e+00 -8.94655287e-01  4.54673290e-01 -8.63096654e-01
  1.32782567e+00 -5.9

: 

# Reading the files with Pandas package

## Reading the test.h5 file

In [ ]:
import pandas as pd

pdtable = pd.read_hdf("/Users/cpare/Downloads/test.h5", key='table')
pdtable

E_0        PX_0        PY_0        PZ_0         E_1        PX_1  \
436  218.364243 -172.341858  110.129105  -76.503624  153.661118 -111.320465   
440  122.238762   26.738468  -91.613998   76.382225  121.227135   17.644758   
441  383.772308  -97.906456   79.640709 -362.426361  200.625992  -54.921326   
444  132.492752  -77.763947  -87.322601  -62.304600   83.946594  -49.450481   
445  730.786987 -209.120010 -193.454315 -672.973877  225.477325  -75.363350   
..          ...         ...         ...         ...         ...         ...   
820  169.716614 -122.102844   36.656090  112.031059  112.158615  -80.692657   
822  287.591492  -81.565056 -140.493576  237.313202  160.357544  -34.246628   
824   91.996681   60.538616  -63.476665   27.734055   93.122139   60.690456   
825  132.474686   35.062359  125.736656   22.593466   61.466259    7.588309   
827   95.355087  -46.626762   25.236219   79.256989   86.610634  -36.374290   

          PY_1        PZ_1         E_2       PX_2  ...  E_199  PX_199  PY_199  \
436  93.167969  -50.390713   76.708054 -56.523701  ...    0.0     0.0     0.0   
440 -93.015450   75.715302   90.420105  21.377417  ...    0.0     0.0     0.0   
441  37.994343 -189.184753  123.247223 -33.828953  ...    0.0     0.0     0.0   
444 -53.823605  -41.288010   28.072624 -19.964916  ...    0.0     0.0     0.0   
445 -66.226990 -201.926651  217.040192 -63.698189  ...    0.0     0.0     0.0   
..         ...         ...         ...        ...  ...    ...     ...     ...   
820  24.224476   74.036636   86.687820 -60.876274  ...    0.0     0.0     0.0   
822 -88.843933  129.028931  105.006508 -30.313942  ...    0.0     0.0     0.0   
824 -61.697636   34.377369   67.617706  33.402180  ...    0.0     0.0     0.0   
825  55.307018   25.722607   53.369095  17.563345  ...    0.0     0.0     0.0   
827  28.903816   73.095024   76.419800 -39.889969  ...    0.0     0.0     0.0   

     PZ_199       truthE     truthPX     truthPY      truthPZ  ttv  \
436     0.0     0.000000    0.000000    0.000000     0.000000    1   
440     0.0     0.000000    0.000000    0.000000     0.000000    1   
441     0.0     0.000000    0.000000    0.000000     0.000000    1   
444     0.0     0.000000    0.000000    0.000000     0.000000    1   
445     0.0     0.000000    0.000000    0.000000     0.000000    1   
..      ...          ...         ...         ...          ...  ...   
820     0.0   832.899963 -572.147461  249.778381   524.242310    1   
822     0.0  1014.205322 -213.806396 -476.465851   852.417358    1   
824     0.0   659.905701  419.718506 -414.999115   239.802658    1   
825     0.0   659.797302   39.736858  593.325745   230.296585    1   
827     0.0  1255.107666 -514.749023  269.764374  1099.081665    1   

     is_signal_new  
436              0  
440              0  
441              0  
444              0  
445              0  
..             ...  
820              1  
822              1  
824              1  
825              1  
827              1  

[404000 rows x 806 columns]

: 

## Reading the val.h5 file

: 

In [ ]:
import torch
import pandas as pd
pdtable2 = pd.read_hdf("/Users/cpare/Downloads/val.h5", key="table")
#pdtable2



torch.tensor(pdtable2.values)


tensor([[ 2.6668e+02,  8.5228e+01, -2.2771e+02,  ...,  0.0000e+00,
          2.0000e+00,  0.0000e+00],
        [ 3.8581e+02,  8.2459e+01,  3.0301e+02,  ...,  0.0000e+00,
          2.0000e+00,  0.0000e+00],
        [ 1.4454e+02, -1.0809e+02,  9.3248e+01,  ...,  0.0000e+00,
          2.0000e+00,  0.0000e+00],
        ...,
        [ 1.4932e+02, -5.7978e+01, -1.3733e+02,  ...,  1.4825e+02,
          2.0000e+00,  1.0000e+00],
        [ 1.9086e+02, -1.6580e+02, -7.4019e+01,  ...,  7.1969e+01,
          2.0000e+00,  1.0000e+00],
        [ 2.1717e+02,  6.4562e+01,  4.2024e+01,  ..., -1.4779e+03,
          2.0000e+00,  1.0000e+00]], dtype=torch.float64)

: 

In [ ]:
pdtable2

E_0        PX_0        PY_0        PZ_0         E_1        PX_1  \
954  266.676880   85.227501 -227.714478  109.539703  145.654129   46.856384   
957  385.807739   82.459038  303.009888 -224.127502  107.484184   15.370172   
959  144.535309 -108.092529   93.247643  -22.612755   70.963295  -21.669872   
970   82.668480   49.805248   -9.679499  -65.267319   58.262596   38.636459   
979  406.581726  186.811081 -345.960571  103.545181   42.170246   19.375856   
..          ...         ...         ...         ...         ...         ...   
79   216.537048 -107.879570  147.704437  115.903809   78.977982  -37.675030   
80   256.309357   73.916145   51.214066  240.016693  220.020920   67.665489   
94   149.320160  -57.977814 -137.329697    8.697165   77.671951  -44.806252   
100  190.856232 -165.798553  -74.019081   58.805752  124.975494 -105.648369   
106  217.169281   64.561562   42.023964 -203.047501  194.615829   57.327908   

           PY_1        PZ_1         E_2       PX_2  ...  E_199  PX_199  \
954 -124.277214   59.789429   76.116646  24.653267  ...    0.0     0.0   
957   85.792786  -62.898380   69.148743  14.434706  ...    0.0     0.0   
959   46.335262  -49.185867   56.287312 -19.737480  ...    0.0     0.0   
970   -7.670141  -42.929283   59.068157  37.110703  ...    0.0     0.0   
979  -35.882679   10.739602   36.417843  12.717323  ...    0.0     0.0   
..          ...         ...         ...        ...  ...    ...     ...   
79    56.436275   40.411144   68.505646 -32.266167  ...    0.0     0.0   
80    39.245872  205.646164  208.380188  59.506413  ...    0.0     0.0   
94   -56.038784   29.748730   47.269886 -24.183697  ...    0.0     0.0   
100  -66.629128    4.225531   46.493565 -23.280176  ...    0.0     0.0   
106   36.736118 -182.316452  174.213791  52.191235  ...    0.0     0.0   

     PY_199  PZ_199       truthE     truthPX     truthPY      truthPZ  ttv  \
954     0.0     0.0     0.000000    0.000000    0.000000     0.000000    2   
957     0.0     0.0     0.000000    0.000000    0.000000     0.000000    2   
959     0.0     0.0     0.000000    0.000000    0.000000     0.000000    2   
970     0.0     0.0     0.000000    0.000000    0.000000     0.000000    2   
979     0.0     0.0     0.000000    0.000000    0.000000     0.000000    2   
..      ...     ...          ...         ...         ...          ...  ...   
79      0.0     0.0   694.652893 -201.456940  455.742981   453.311981    2   
80      0.0     0.0  1164.048096  460.885040  117.631760  1048.503418    2   
94      0.0     0.0   634.966675 -208.080597 -555.733948   148.248032    2   
100     0.0     0.0   554.314880 -447.911743 -268.416351    71.968674    2   
106     0.0     0.0  1602.284302  487.335297  337.785370 -1477.923828    2   

     is_signal_new  
954              0  
957              0  
959              0  
970              0  
979              0  
..             ...  
79               1  
80               1  
94               1  
100              1  
106              1  

[403000 rows x 806 columns]

: 

In [ ]:
values = pdtable.values
values.shape[1]

806

: 

In [ ]:
particle_feats = values[:, :800].reshape(-1, 200, 4)
jet_feats = values[:, 800:804]
isTop = values[:, -1]
print(jet_feats)

[[   0.            0.            0.            0.        ]
 [   0.            0.            0.            0.        ]
 [   0.            0.            0.            0.        ]
 ...
 [ 659.90570068  419.71850586 -414.99911499  239.80265808]
 [ 659.79730225   39.73685837  593.32574463  230.29658508]
 [1255.10766602 -514.74902344  269.76437378 1099.08166504]]


: 

In [ ]:
print(particle_feats)

[[[ 218.36424255 -172.34185791  110.12910461  -76.50362396]
  [ 153.66111755 -111.32046509   93.16796875  -50.39071274]
  [  76.70805359  -56.52370071   46.12729263  -23.69534874]
  ...
  [   0.            0.            0.            0.        ]
  [   0.            0.            0.            0.        ]
  [   0.            0.            0.            0.        ]]

 [[ 122.2387619    26.73846817  -91.61399841   76.38222504]
  [ 121.2271347    17.64475822  -93.01544952   75.71530151]
  [  90.42010498   21.37741661  -68.01097107   55.61753082]
  ...
  [   0.            0.            0.            0.        ]
  [   0.            0.            0.            0.        ]
  [   0.            0.            0.            0.        ]]

 [[ 383.77230835  -97.90645599   79.64070892 -362.42636108]
  [ 200.62599182  -54.92132568   37.9943428  -189.18475342]
  [ 123.2472229   -33.82895279   23.79285812 -116.1007309 ]
  ...
  [   0.            0.            0.            0.        ]
  [   0.          

: 

In [ ]:
import torch
import numpy as np

torch.load("val.pt")

tensor([  0.,   7.,  14.,  22.,  30.,  38.,  46.,  54.,  62.,  70.,  79.,  88.,
         96., 104., 111., 119., 127., 135., 142., 150., 158., 166., 173., 181.,
        189., 197., 205., 214., 222., 230., 239., 247., 255., 263., 271., 279.,
        286., 294., 302., 310., 318., 326., 334., 342., 350., 357., 365., 373.,
        381., 389., 397., 405., 412., 420., 428., 435., 443., 450., 458., 466.,
        474., 481., 488., 496., 503., 510., 517., 524., 531., 539., 547., 554.,
        562., 570., 578., 586., 594., 602., 609., 617., 625., 632., 640., 647.,
        655., 663., 671., 679., 686., 694., 702., 709., 717., 725., 732., 740.,
        748., 756., 764., 772., 780., 788., 796., 804., 812., 819., 827., 835.,
        843., 851., 859., 866., 874., 882., 890., 897., 905., 913., 920., 928.,
        936., 944., 952., 960., 968., 976., 984., 992.,   0.,   7.,  15.,  23.,
         31.,  39.,  46.,  54.,  61.,  69.,  76.,  84.,  92.,  99., 107., 115.,
        122., 130., 138., 145., 153., 16

: 

In [ ]:
torch.load('val.pt')

tensor([  0.,   7.,  14.,  22.,  30.,  38.,  46.,  54.,  62.,  70.,  79.,  88.,
         96., 104., 111., 119., 127., 135., 142., 150., 158., 166., 173., 181.,
        189., 197., 205., 214., 222., 230., 239., 247., 255., 263., 271., 279.,
        286., 294., 302., 310., 318., 326., 334., 342., 350., 357., 365., 373.,
        381., 389., 397., 405., 412., 420., 428., 435., 443., 450., 458., 466.,
        474., 481., 488., 496., 503., 510., 517., 524., 531., 539., 547., 554.,
        562., 570., 578., 586., 594., 602., 609., 617., 625., 632., 640., 647.,
        655., 663., 671., 679., 686., 694., 702., 709., 717., 725., 732., 740.,
        748., 756., 764., 772., 780., 788., 796., 804., 812., 819., 827., 835.,
        843., 851., 859., 866., 874., 882., 890., 897., 905., 913., 920., 928.,
        936., 944., 952., 960., 968., 976., 984., 992.,   0.,   7.,  15.,  23.,
         31.,  39.,  46.,  54.,  61.,  69.,  76.,  84.,  92.,  99., 107., 115.,
        122., 130., 138., 145., 153., 16

: 

In [ ]:
import torch

torch.load('val.pt')

: 